### ISSUE TITLE
Simplices near the time boundary disappear after subdivision for 4d model

### ISSUE THREAD

**Issue by jamievicary** [homotopy-io/homotopy-rs#342]

**Comment by calintat** [comment]
@jamievicary do you still have the workspace? I think it's somewhere in the Element group chat but I can't find it.

**Comment by jamievicary** [comment]
Yes here you go. The issue first appears at subdivision=1. Everything is fine at subdivision=0.
[filename_todo.zip](https://github.com/homotopy-io/homotopy-rs/files/7944335/filename_todo.zip)

**Comment by doctorn** [comment]
This is a boundary labelling bug

**Comment by jamievicary** [comment]
A great that's very clear.

**Comment by calintat** [comment]
Ah, this is very interesting. But if we fixed that boundary, we would get some other weird behaviour.

**Comment by calintat** [comment]
If you fix the boundary completely, then it won't be smoothed.

I wonder if the problem is that our current boundary label is not rich enough. We can't distinguish between a point that can only move horizontally and a point that can only move vertically (they both get boundary label 1 meaning they can move along edges). Does this make sense?

**Comment by jamievicary** [comment]
I'm sure there are subtleties I'm not seeing, but the basic point is that if a point is marked as being on a boundary, it should never be moved off the boundary. This is a trivial adjustment to any smoothing algorithm: after a smoothing step, check all the boundary points and move them back onto the boundary if necessary by changing one coordinate. Of course, it would probably make more sense not to move them off the boundary in the first place.

**Comment by doctorn** [comment]
> I'm sure there are subtleties I'm not seeing, but the basic point is that if a point is marked as being on a boundary, it should never be moved off the boundary. This is a trivial adjustment to any smoothing algorithm: after a smoothing step, check all the boundary points and move them back onto the boundary if necessary by changing one coordinate. Of course, it would probably make more sense not to move them off the boundary in the first place.
Just moving a point back onto a boundary is not sufficient, as this breaks local continuity. The notion of 'boundary' which Calin is referring to here is not boundary in the sense of the boundary of a diagram, but the flavour of n-manifold on which a point sits. The naming of this is something we've inherited from Akvile's original implementation of subdivision, but maybe deserves a better name!

**Comment by jamievicary** [comment]
Ok, but that's just a semantic issue. The point is that if any vertex starts on the "true boundary" of the diagram, it should stay there during the entire subdivision.

**Comment by calintat** [comment]
This was mostly fixed by 172bbbd. The edges no longer disappear but they stretch as they approach the boundary.

**Comment by jamievicary** [comment]
Calin I'm not sure this should be closed yet. We're still seeing this to some extent right?

**Comment by calintat** [comment]
> Calin I'm not sure this should be closed yet. We're still seeing this to some extent right?

I created a new issue for the boundary labelling problem.
