### ISSUE TITLE
Clicking and dragging at boundary not deterministic

### ISSUE THREAD

**Issue by jamievicary** [homotopy-io/homotopy-rs#35]
I'm having some very weird issues with nondeterministic behaviour when clicking and dragging at the boundary. Take a look at this video: https://youtu.be/3SKC4AJHXKk

Move 1 purple onto yellow, works ok
Move 2 purple off yellow, DOESN'T WORK
Move 3 purple onto yellow, works ok
Move 4 purple off yellow, works ok BUT WHY? SHOULD BE IDENTICAL TO MOVE 2
Moves 5, 6, 7, 8 work ok, all purple/red
Now to the bottom of the diagram
Move 9 red onto yellow, works ok
Move 10 red off yellow, DOESN'T WORK
Move 11 red onto yellow, works ok
Move 12 red off yellow, DOESN'T WORK (same as move 10)
Move 13 red onto yellow, works ok
Move 14 red off yellow, works ok BUT WHY? SHOULD BE IDENTICAL TO MOVES 10, 12
Move 15 yellow onto red, works ok
Move 15 yellow off red, DOESN'T WORK

**Comment by jamievicary** [comment]
Could it be an issue with the system not correctly detecting the drag at the "top" strand. (Doesn't explain the nondeterminism of course.)

**Comment by jamievicary** [comment]
[filename_todo (14).zip](https://github.com/homotopy-io/homotopy-rs/files/6346264/filename_todo.14.zip)
Here is the workspace.

**Comment by zrho** [comment]
I think that this is fixed now. It turns out it was deterministic, but the direction a homotopy was performed as the response to a horizontal drag was determined by checking if the drag was oriented upwards or downwards as makes sense for vertical drags.

**Comment by jamievicary** [comment]
Ahh right, I didn't think of that. So deterministic yet, but in a way which
was sensitive to the thermal entropy of my mouse as I attempt to move it
perfectly horizontally along the table :).

**Comment by jamievicary** [comment]
Unfortunately this issue still exists. Try creating a braid diagram and dragging a lower wire end left-and-slightly-up. It braids to the right.

**Comment by zrho** [comment]
9bfc110da4221ed4b99637b7c8144febcf8993f3 should have fixed this. The code that determines homotopies as well as attachments does deserve a proper cleanup though.
